### ISSUE TITLE
Many 500 errors sent to the Matchbox node this week

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#154]
I've been notified that our server has been sending error messages to other nodes this week. Needs to be checked urgently!

**Comment by northwestwitch** [comment]
Both stage and prod servers are up and running:

https://patientmatcher.scilifelab.se/metrics
https://patientmatcher-stage.scilifelab.se/metrics

I'll to investigate into the database

**Comment by northwestwitch** [comment]
Must be this error on the server, recreated on a local instance:

```
(mme) chiararasi@n129-p71:~/Documents/work/GITs/patientMatcher$ pmatcher run -p 9020
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:patientMatcher.server:Configuring app from environment variable
WARNING:patientMatcher.server:Environment variable settings not found, configuring from instance file.
INFO:patientMatcher.server:database connection info:Database(MongoClient(host=['127.0.0.1:27017'], document_class=dict, tz_aware=False, connect=True), 'pmatcher')
INFO:werkzeug: * Running on http://127.0.0.1:9020/ (Press CTRL+C to quit)
INFO:patientMatcher.auth.auth:Authorized client with id "dummynode" submits a POST request
INFO:patientMatcher.parse.patient:Validating against SCHEMA #/definitions/request
INFO:patientMatcher.server.views:Matching a query patient against database
INFO:patientMatcher.match.handler:Matching phenotypes against database patients..
INFO:patientMatcher.match.phenotype_matcher:

###### Running phenotype matcher module ######
INFO:patientMatcher.match.phenotype_matcher:Creating HPO information content
INFO:patient_similarity.hpo:Parsing graph...
INFO:patient_similarity.hpo:HPO version: 1.2
INFO:patient_similarity.hpo:Found 15371 HP nodes (19044 terms) in graph
INFO:patient_similarity.hpo:Filtering to the 15371 nodes descendant of HP:0000001 (All)...
ERROR:patient_similarity.disease:Error parsing frequency: 'frequencyhpo'
WARNING:root:Found conflicting frequencies (None, 0.025) for same disease-phenotype: OMIM:105650 - HP:0000316 (taking larger)
ERROR:patientMatcher.server:Exception on /match [POST]
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask_negotiate.py", line 14, in wrapper
    return fn(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask_negotiate.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/server/views.py", line 287, in match_internal
    match_obj = internal_matcher(
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/handler.py", line 72, in internal_matcher
    pheno_matches = phenomatch(
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/phenotype_matcher.py", line 46, in match
    diseases = Diseases(path_to_phenotype_annotations)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/patient_similarity/disease.py", line 63, in __init__
    diseases = dict(self.iter_diseases(filename, filter_db=db))
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/patient_similarity/disease.py", line 115, in iter_diseases
    alt_diseases = db_re.findall(tokens[5].strip())
IndexError: list index out of range
```

Reflecting in this error when you launch the request:
![image](https://user-images.githubusercontent.com/28093618/100337642-f338eb80-2fd7-11eb-8d31-e2ba9ab1b3f2.png)

**Comment by northwestwitch** [comment]
This is so weird, not it looks like it's working again..

**Comment by northwestwitch** [comment]
The error above was probably due to the fact that I had removed a file while testing. 
I can't reproduce any error on my local instance: Unfortunately we don't have any logging system in place for patientMatcher on clinical-db. I don't know if the logging if it's worth to fix it now that we are switching to the new server (for sure we should have it there) but that would have helped. I'll ask the contact from Matchbox if the error continues and I'll see.

**Comment by northwestwitch** [comment]
Closing this and opening specific error/s
