### ISSUE TITLE
AttributeError: 'HTTPResponse' object has no attribute 'get' when Ensembl is down

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#155]
```
209.6.206.10 - - [25/Nov/2020:17:18:31 +0100] "POST /match HTTP/1.0" 400 23 "-" "PostmanRuntime/7.26.5"
INFO:patientMatcher.auth.auth:Authorized client with id "matchbox" submits a POST request
INFO:patientMatcher.parse.patient:Validating against SCHEMA #/definitions/request
INFO:patientMatcher.utils.ensembl_rest_client:Request failed for url https://grch37.rest.ensembl.org/lookup/id/ENSG00000279689: Error: HTTP Error 400: Bad Request

[2020-11-25 17:18:55 +0100] [42932] [ERROR] Error handling request /match
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask_negotiate.py", line 14, in wrapper
    return fn(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask_negotiate.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/server/views.py", line 246, in match_internal
    query_patient = controllers.check_request(current_app.db, request)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/server/controllers.py", line 88, in check_request
    convert_to_ensembl = True)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/parse/patient.py", line 27, in mme_patient
    format_genes(json_patient)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/parse/patient.py", line 123, in format_genes 
    symbol = ensembl_to_symbol(gene)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/utils/gene.py", line 52, in ensembl_to_symbol
    return result.get('display_name', None)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/tempfile.py", line 478, in __getattr__
    a = getattr(file, name)
AttributeError: 'HTTPResponse' object has no attribute 'get'
```

**Comment by northwestwitch** [comment]
Fixed in #156
