### ISSUE TITLE
 Authentication failed while testing the new version on scout stage

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#159]
Version 2.2 works just fine so it must be something in version 2.3. It needs fixing before I deploy on prod.

```
INFO:patientMatcher.server:database connection info:Database(MongoClient(host=['127.0.0.1:27030'], document_class=dict, tz_aware=False, connect=True), 'pmatcher-stage')
[2020-12-01 16:07:57 +0100] [4077] [ERROR] Error handling request /patient/add
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask_negotiate.py", line 14, in wrapper
    return fn(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/flask_negotiate.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/patientMatcher/server/views.py", line 27, in add
    formatted_patient = controllers.check_request(current_app.db, request)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/patientMatcher/server/controllers.py", line 74, in check_request
    if not authorize(database, request):
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/patientMatcher/auth/auth.py", line 20, in authorize
    authorized = database["clients"].find_one(query)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/collection.py", line 1225, in find_one
    for result in cursor.limit(-1):
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/cursor.py", line 1169, in next
    if len(self.__data) or self._refresh():
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/cursor.py", line 1085, in _refresh
    self.__send_message(q)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/cursor.py", line 924, in __send_message
    **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1029, in _send_message_with_response
    exhaust)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1040, in _reset_on_error
    return func(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/server.py", line 85, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/pool.py", line 920, in get_socket
    sock_info.check_auth(all_credentials)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/pool.py", line 609, in check_auth
    auth.authenticate(credentials, self)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/hiseq.clinical/miniconda/envs/S_pmatcher/lib/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
127.0.0.1 - - [01/Dec/2020:16:07:57 +0100] "POST /patient/add HTTP/1.1" 500 0 "-" "-"
```

**Comment by northwestwitch** [comment]
I don't understand. This error is likely do to the fact that the app can't connect to mongo on clinical-db stage, but the connection code hasn't changed and the connection parameters in the config file haven't been touched in a year.
