### ISSUE TITLE
Unsupported operand type(s) for +: 'NoneType' and 'int' in genome matcher module

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#167]
An error reported from a colleague from the MatchBox node (Broad institute). Needs fixing ASAP!

```
###### Running genome matcher module ######
2021-01-05 17:33:56 clinical-db.scilifelab.se patientMatcher.match.genotype_matcher[22370] INFO Query patient has 1 genotype features.
2021-01-05 17:33:56 clinical-db.scilifelab.se patientMatcher.match.genotype_matcher[22370] INFO Each GT feature will contribute with a weight of 0.75 to a total GT score (max GT score is 0.75)
[2021-01-05 17:33:56 +0100] [22370] [ERROR] Error handling request /match
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 228, in __call__
    return self.app(environ, start_response)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask_negotiate.py", line 14, in wrapper
    return fn(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/flask_negotiate.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/server/views.py", line 288, in match_internal
    current_app.db, query_patient, max_pheno_score, max_geno_score, max_results, score_threshold
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/match/handler.py", line 83, in internal_matcher
    geno_matches = genomatch(database, patient_obj["genomicFeatures"], max_geno_score)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/match/genotype_matcher.py", line 49, in match
    variants = gtfeatures_to_variants(gt_features)
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/parse/patient.py", line 235, in gtfeatures_to_variants
    lifted_variants = lift_variant(feature["variant"])
  File "/home/hiseq.clinical/miniconda/envs/P_pmatcher/lib/python3.6/site-packages/patientMatcher/parse/patient.py", line 196, in lift_variant
    variant.get("end") + 1,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
127.0.0.1 - - [05/Jan/2021:17:33:56 +0100] "POST /match HTTP/1.0" 500 0 "-" "-"
```

**Comment by northwestwitch** [comment]
To reproduce the error, send a match request with no end coordinate (didn't realize that only start coordinate is required).

```
curl -X POST \
  -H 'X-Auth-Token: custom_token' \
  -H 'Content-Type: application/vnd.ga4gh.matchmaker.v1.0+json' \
  -H 'Accept: application/vnd.ga4gh.matchmaker.v1.0+json' \
  -d '{"patient":{
    "id":"patient_id",
    "contact": {"name":"Contact Name", "href":"mailto:contact_name@mail.com"},
    "features":[{"id":"HP:0011344"}],
    "genomicFeatures":[{"gene":{"id":"GRIN2A"}, "variant":{"assembly":"GRCh38", "referenceName":"16", "start":9768996,
    "referenceBases":"T", "alternateBases":"C"}}]
  }}' localhost:9020/match
```



 ```
 File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask_negotiate.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/server/views.py", line 287, in match_internal
    match_obj = internal_matcher(
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/handler.py", line 83, in internal_matcher
    geno_matches = genomatch(database, patient_obj["genomicFeatures"], max_geno_score)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/genotype_matcher.py", line 49, in match
    variants = gtfeatures_to_variants(gt_features)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/parse/patient.py", line 235, in gtfeatures_to_variants
    lifted_variants = lift_variant(feature["variant"])
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/parse/patient.py", line 196, in lift_variant
    variant.get("end") + 1,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by northwestwitch** [comment]
The fix for this is now deployed on stage and master. I'll check the logs later to make sure that everything is fine. I need to set up an email report when these things happen so I'll be notified when the app crashes.
