### ISSUE TITLE
ZeroDivisionError: division by zero in simgic algorithm when comparing HPO terms

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#181]
I've noticed about this bug while working on a code refactoring on Scout:

```
2021-03-22 17:19:52 n129-p71.local patientMatcher.server[86675] ERROR Exception on /match [POST]
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask_negotiate.py", line 14, in wrapper
    return fn(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask_negotiate.py", line 27, in wrapper
    return fn(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/server/views.py", line 287, in match_internal
    match_obj = internal_matcher(
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/handler.py", line 72, in internal_matcher
    pheno_matches = phenomatch(
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/phenotype_matcher.py", line 70, in match
    similarity = evaluate_pheno_similariy(
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/phenotype_matcher.py", line 121, in evaluate_pheno_similariy
    hpo_score = similarity_wrapper(hpoic, hpo, max_hpo_score, hpo_terms, matching_hpo_terms)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/match/phenotype_matcher.py", line 167, in similarity_wrapper
    score_obj = compare_patients(
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/patient_similarity/__main__.py", line 132, in compare_patients
    out['simgic'] = hpoic.information_content(common_ancestors) / hpoic.information_content(all_ancestors)
ZeroDivisionError: division by zero
```

**Comment by northwestwitch** [comment]
Aha! This happens probably because the phenotype annotation was not correctly downloaded to the server:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /jenkins/job/hpo.annotations/lastStableBuild/artifact/misc/phenotype_annotation.tab. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

I should fix the download link and the error handling!
