### ISSUE TITLE
Deprecated werkzeug.contrib error with werkzeug>=1.0.0

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#245]
This error occurs when running the Dockererized app via gunicorn, where Werkzeug==2.0.2

```
worker@5588d138fa13:~/app$ gunicorn --chdir patientMatcher/server auto:app
[2021-12-06 09:05:02 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2021-12-06 09:05:02 +0000] [11] [INFO] Listening at: http://127.0.0.1:8000 (11)
[2021-12-06 09:05:02 +0000] [11] [INFO] Using worker: sync
[2021-12-06 09:05:02 +0000] [13] [INFO] Booting worker with pid: 13
[2021-12-06 09:05:02 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/worker/app/patientMatcher/server/auto.py", line 1, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.contrib'
[2021-12-06 09:05:02 +0000] [13] [INFO] Worker exiting (pid: 13)
[2021-12-06 09:05:02 +0000] [11] [INFO] Shutting down: Master
[2021-12-06 09:05:02 +0000] [11] [INFO] Reason: Worker failed to boot.
worker@5588d138fa13:~/app$
```

**Comment by northwestwitch** [comment]
This was fixed in #246
