### ISSUE TITLE
Can't download phenotype_annotation.tab

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#318]
```
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/pmatcher/bin/pmatcher", line 33, in <module>
    sys.exit(load_entry_point('patientMatcher', 'console_scripts', 'pmatcher')())
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/cli/update.py", line 81, in resources
    update_resources(test)
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/utils/update.py", line 18, in update_resources
    r = requests.get(url, stream=True)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/pmatcher/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='purl.obolibrary.org', port=443): Max retries exceeded with url: /obo/hp/hpoa/phenotype_annotation.tab (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f931096ceb0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

**Comment by northwestwitch** [comment]
Might be because they have migrated to a new file format, reference: https://hpo-annotation-qc.readthedocs.io/en/latest/annotationFormat.html

**Comment by northwestwitch** [comment]
Difference between the 2 files:

New file:
```
#DatabaseID	DiseaseName	Qualifier	HPO_ID	Reference	Evidence	Onset	Frequency	Sex	Modifier	Aspect	Biocuration
OMIM:203400	Corticosterone methyloxidase type I deficiency		HP:0002013	OMIM:203400	IEA					P	HPO:iea[2009-02-17]
OMIM:203400	Corticosterone methyloxidase type I deficiency		HP:0002153	OMIM:203400	IEA					P	HPO:iea[2009-02-17]
OMIM:203400	Corticosterone methyloxidase type I deficiency		HP:0000848	OMIM:203400	IEA					P	HPO:iea[2009-02-17]
OMIM:203400	Corticosterone methyloxidase type I deficiency		HP:0001508	OMIM:203400	IEA					P	HPO:iea[2009-02-17]
OMIM:203400	Corticosterone methyloxidase type I deficiency		HP:0001944	OMIM:203400	IEA					P	HPO:iea[2009-02-17]
```

Old file:
```
#disease-db	disease-identifier	disease-name	negation	HPO-ID	reference	evidence-code	onset	frequencyHPO	modifier	sub-ontology	alt-names	curators	frequencyRaw	sex
DECIPHER	1	Wolf-Hirschhorn syndrome		HP:0000252	DECIPHER:1	IEA			 	P	WOLF-HIRSCHHORN SYNDROME	HPO:skoehler[2013-05-29]	-	-
DECIPHER	1	Wolf-Hirschhorn syndrome		HP:0001249	DECIPHER:1	IEA			 	P	WOLF-HIRSCHHORN SYNDROME	HPO:skoehler[2013-05-29]	-	-
DECIPHER	1	Wolf-Hirschhorn syndrome		HP:0001250	DECIPHER:1	IEA			 	P	WOLF-HIRSCHHORN SYNDROME	HPO:skoehler[2013-05-29]	-	-
DECIPHER	1	Wolf-Hirschhorn syndrome		HP:0001252	DECIPHER:1	IEA			 	P	WOLF-HIRSCHHORN SYNDROME	HPO:skoehler[2013-05-29]	-	-
DECIPHER	1	Wolf-Hirschhorn syndrome		HP:0001518	DECIPHER:1	IEA			 	P	WOLF-HIRSCHHORN SYNDROME	HPO:skoehler[2013-05-29]	-	-
```
