### ISSUE TITLE
Newest resource file not correctly parsed

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#327]
If you update the resource files with command `pmatcher update resources` and try starting the service you get this error:

```
2023-08-11 08:38:57 n177-p182.local patientMatcher.utils.hpo[37606] INFO Parsed 17272 HPO terms into HPO nodes from resource file
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/mme/bin/pmatcher", line 33, in <module>
    sys.exit(load_entry_point('patientMatcher', 'console_scripts', 'pmatcher')())
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/Users/chiararasi/miniconda3/envs/mme/lib/python3.8/site-packages/flask/cli.py", line 301, in load_app
    app = self.create_app()
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/server/__init__.py", line 99, in create_app
    extensions.diseases.init_app()
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/utils/disease.py", line 57, in init_app
    self._parse_diseases()
  File "/Users/chiararasi/Documents/work/GITs/patientMatcher/patientMatcher/utils/disease.py", line 131, in _parse_diseases
    pheno_id = items[0].split(":")[1]
IndexError: list index out of range
```

**Comment by northwestwitch** [comment]
Ah, easy fix thankfully!

The old diseases files contained a # at the beginning of all commented lines: 

<img width="416" alt="image" src="https://github.com/Clinical-Genomics/patientMatcher/assets/28093618/8007e14c-a919-4b11-b4c8-978963aabe63">

The newest file is missing the # on the header:

<img width="550" alt="image" src="https://github.com/Clinical-Genomics/patientMatcher/assets/28093618/dba2c4a1-3081-4a46-bbd0-1c93e9b9271b">
